const data = {
    status: "OK",
    request_id: "e545ea48-fa33-4520-aae1-2f8af5209ba2",
    parameters: {
      query: "Phone",
      country: "US",
      sort_by: "RELEVANCE",
      page: 1
    },
    data: {
      total_products: 10727,
      country: "US",
      domain: "www.amazon.com",
      products: [
        {
          asin: "B0BQ118F2T",
          product_title: "Moto G Play 2023 3-Day Battery Unlocked Made for US 3/32GB 16MP Camera Navy Blue",
          product_price: "$99.99",
          product_original_price: "$169.99",
          currency: "USD",
          product_star_rating: "4",
          product_num_ratings: 2950,
          product_url: "https://www.amazon.com/dp/B0BQ118F2T",
          product_photo: "https://m.media-amazon.com/images/I/61K1Fz5LxvL._AC_UY654_FMwebp_QL65_.jpg",
          product_num_offers: 12,
          product_minimum_offer_price: "$81.31",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: true,
          climate_pledge_friendly: false,
          sales_volume: "5K+ bought in past month",
          delivery: "FREE delivery Sat, Aug 10 Or fastest delivery Thu, Aug 8",
          has_variations: true,
          brand: "Moto",
          category: "mobile",
        },
        {
          asin: "B0CHH6X6H2",
          product_title: "Total by Verizon | Samsung Galaxy A03s | Locked | 32GB | 5000mAh Battery | 48MP Main Camera | 6.5-in. HD+Infinity-V Display | Black",
          product_price: "$49.88",
          product_original_price: null,
          currency: "USD",
          product_star_rating: "3.9",
          product_num_ratings: 213,
          product_url: "https://www.amazon.com/dp/B0CHH6X6H2",
          product_photo: "https://m.media-amazon.com/images/I/812woqv69CL._AC_UY654_FMwebp_QL65_.jpg",
          product_num_offers: 1,
          product_minimum_offer_price: "$49.88",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: true,
          climate_pledge_friendly: false,
          sales_volume: "2K+ bought in past month",
          delivery: "FREE delivery Sat, Aug 10 Or fastest delivery Thu, Aug 8",
          has_variations: false,
          brand: "Samsung",
          category: "mobile",
        },
        {
          asin: "B0CN1QSH8Q",
          product_title: "SAMSUNG Galaxy A15 5G A Series Cell Phone, 128GB Unlocked Android Smartphone, AMOLED Display, Expandable Storage, Knox Security, Super Fast Charging, Hi-Res Camera, US Version, 2024, Blue Black",
          product_price: "$199.99",
          product_original_price: null,
          currency: "USD",
          product_star_rating: "4.1",
          product_num_ratings: 435,
          product_url: "https://www.amazon.com/dp/B0CN1QSH8Q",
          product_photo: "https://m.media-amazon.com/images/I/61s0ZzwzSCL._AC_UY654_FMwebp_QL65_.jpg",
          product_num_offers: 2,
          product_minimum_offer_price: "$170.19",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: true,
          climate_pledge_friendly: true,
          sales_volume: "3K+ bought in past month",
          delivery: "FREE delivery Sat, Aug 10 Or fastest delivery Thu, Aug 8",
          has_variations: true,
          brand: "Samsung",
          category: "mobile",
        },
        {
          asin: "B0BZ9XNBRB",
          product_title: "Google Pixel 7a - Unlocked Android Cell Phone - Smartphone with Wide Angle Lens and 24-Hour Battery - 128 GB – Charcoal",
          product_price: "$338.99",
          product_original_price: "$499.00",
          currency: "USD",
          product_star_rating: "4.3",
          product_num_ratings: 2273,
          product_url: "https://www.amazon.com/dp/B0BZ9XNBRB",
          product_photo: "https://m.media-amazon.com/images/I/61r7cCpQPlL._AC_UY654_FMwebp_QL65_.jpg",
          product_num_offers: 31,
          product_minimum_offer_price: "$289.99",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: false,
          climate_pledge_friendly: false,
          sales_volume: "10K+ bought in past month",
          delivery: "FREE delivery Thu, Aug 8",
          has_variations: true,
          brand: "Google",
          category: "mobile",
        },
        {
          asin: "B0CSB22F9C",
          product_title: "Samsung Galaxy A15 (SM-155M/DSN), 128GB 6GB RAM, Dual SIM, Factory Unlocked GSM, International Version (Wall Charger Bundle) (Light Blue)",
          product_price: "$136.99",
          product_original_price: null,
          currency: "USD",
          product_star_rating: "4.2",
          product_num_ratings: 600,
          product_url: "https://www.amazon.com/dp/B0CSB22F9C",
          product_photo: "https://m.media-amazon.com/images/I/51rp0nqaPoL._AC_UY654_FMwebp_QL65_.jpg",
          product_num_offers: 11,
          product_minimum_offer_price: "$128.17",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: true,
          climate_pledge_friendly: false,
          sales_volume: "4K+ bought in past month",
          delivery: "FREE delivery Sat, Aug 10 Or fastest delivery Thu, Aug 8",
          has_variations: false,
          brand: "Samsung",
          category: "mobile",
        },
        {
          asin: "B0CHH1N9VY",
          product_title: "TracFone | Motorola Moto g Pure | Locked | 32GB | 4000 mAh Battery | 13 MP Dual Camera System | 6.5\" Max Vision HD+ Display | Blue",
          product_price: "$49.54",
          product_original_price: null,
          currency: "USD",
          product_star_rating: "4.2",
          product_num_ratings: 2774,
          product_url: "https://www.amazon.com/dp/B0CHH1N9VY",
          product_photo: "https://m.media-amazon.com/images/I/71zGrrAe5NL._AC_UY654_FMwebp_QL65_.jpg",
          product_num_offers: 1,
          product_minimum_offer_price: "$49.54",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: true,
          climate_pledge_friendly: false,
          sales_volume: "500+ bought in past month",
          delivery: "FREE delivery Sat, Aug 10 Or fastest delivery Thu, Aug 8",
          has_variations: false,
          brand: "TracFone",
          category: "mobile",
        },
        {
          asin: "B088NQXD8T",
          product_title: "Apple iPhone SE 2nd Generation, US Version, 64GB, Black - Unlocked (Renewed)",
          product_price: "$140.99",
          product_original_price: "$156.86",
          currency: "USD",
          product_star_rating: "4.3",
          product_num_ratings: 18002,
          product_url: "https://www.amazon.com/dp/B088NQXD8T",
          product_photo: "https://m.media-amazon.com/images/I/61JNofhHZZL._AC_UY654_FMwebp_QL65_.jpg",
          product_num_offers: 42,
          product_minimum_offer_price: "$103.89",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: false,
          product_availability: "Only 1 left in stock - order soon.",
          climate_pledge_friendly: true,
          sales_volume: "2K+ bought in past month",
          delivery: "FREE deliveryOnly 1 left in stock - order soon.",
          has_variations: true,
          brand: "Apple",
          category: "mobile",
        },
        {
          asin: "B0CTD42NJZ",
          product_title: "SAMSUNG Galaxy A15 5G (SM-156M/DSN), 256GB 8GB RAM, Dual SIM, Factory Unlocked GSM, International Version (Wall Charger Bundle) (Light Blue)",
          product_price: "$178.50",
          product_original_price: "$199.00",
          currency: "USD",
          product_star_rating: "4.3",
          product_num_ratings: 87,
          product_url: "https://www.amazon.com/dp/B0CTD42NJZ",
          product_photo: "https://m.media-amazon.com/images/I/31bNhi6E3eL._AC_UY650_FMwebp_QL65_.jpg",
          product_num_offers: 5,
          product_minimum_offer_price: "$178.50",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: false,
          climate_pledge_friendly: false,
          sales_volume: "1K+ bought in past month",
          delivery: "FREE delivery Sat, Aug 10 Or fastest delivery Thu, Aug 8",
          has_variations: false,
          brand: "SAMSUNG",
          category: "mobile",
        },
        {
          asin: "B0B3JYX32K",
          product_title: "Google Pixel 7 - Unlocked Android 5G Smartphone - Wide and Telephoto Lens - 24-Hour Battery - 128GB - Obsidian",
          product_price: "$528.00",
          product_original_price: "$599.00",
          currency: "USD",
          product_star_rating: "4.3",
          product_num_ratings: 10047,
          product_url: "https://www.amazon.com/dp/B0B3JYX32K",
          product_photo: "https://m.media-amazon.com/images/I/91pcVNp25mL._AC_UY654_FMwebp_QL65_.jpg",
          product_num_offers: 34,
          product_minimum_offer_price: "$452.00",
          is_best_seller: false,
          is_amazon_choice: false,
          is_prime: false,
          climate_pledge_friendly: true,
          sales_volume: "3K+ bought in past month",
          delivery: "FREE delivery Thu, Aug 8",
          has_variations: true,
          brand: "Google",
          category: "mobile",
        }
      ],
      page: 1
    }
  };
  
  export default data;
  